// Package storage puts files somewhere and hands back URLs — the one part of
// the system that owns bytes rather than rows.
//
// Two backends, one interface:
//
//   - R2 (S3-compatible, via aws-sdk-go-v2) when R2_* credentials are set —
//     production. Reads go out as presigned GET URLs, so a bucket never has to
//     be public.
//   - Local disk (./uploads) otherwise — dev and UAT. Files are served by the
//     API itself under /uploads, so the whole photo/document flow works on a
//     laptop with nothing configured.
//
// Callers store the KEY on their rows, never the URL: a URL is minted at read
// time by URL(), which is what lets the backend change without a data
// migration (M18 — A18.1).
package storage

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	uberfx "go.uber.org/fx"

	"github.com/bboyzchecken/rove/apps/api/pkg/core"
)

type Service interface {
	// Put stores the object and returns the key it was stored under.
	Put(ctx context.Context, bucket, key string, body io.Reader, contentType string) error
	// URL returns something a browser can GET for a while: a presigned R2 URL,
	// or a plain /uploads path in local mode.
	URL(ctx context.Context, bucket, key string) (string, error)
	Delete(ctx context.Context, bucket, key string) error
	// Configured reports whether a real bucket is behind this service.
	Configured() bool
}

// ErrNotConfigured survives for callers that still branch on it.
var ErrNotConfigured = errors.New("storage: R2 is not configured")

// presignTTL is how long a minted read URL stays valid. Seven days is the
// SigV4 maximum; the app re-mints on every payload anyway.
const presignTTL = 7 * 24 * time.Hour

func New(cfg core.Config) Service {
	r2 := cfg.R2
	if r2.Endpoint != "" && r2.AccessKey != "" && r2.SecretKey != "" {
		client, presigner, err := newR2Client(r2)
		if err == nil {
			return &r2Service{client: client, presigner: presigner}
		}
	}
	return &localService{cfg: cfg, root: "uploads"}
}

var Module = uberfx.Module("services.storage", uberfx.Provide(New))

/* ---------------------------------------------------------------- R2 ------ */

type r2Service struct {
	client    *s3.Client
	presigner *s3.PresignClient
}

func newR2Client(cfg core.R2Config) (*s3.Client, *s3.PresignClient, error) {
	region := cfg.Region
	if region == "" {
		region = "auto"
	}
	awsCfg, err := awsconfig.LoadDefaultConfig(context.Background(),
		awsconfig.WithRegion(region),
		awsconfig.WithCredentialsProvider(
			credentials.NewStaticCredentialsProvider(cfg.AccessKey, cfg.SecretKey, ""),
		),
	)
	if err != nil {
		return nil, nil, err
	}

	client := s3.NewFromConfig(awsCfg, func(o *s3.Options) {
		o.BaseEndpoint = aws.String(cfg.Endpoint)
		// R2 wants path-style addressing.
		o.UsePathStyle = true
	})
	return client, s3.NewPresignClient(client), nil
}

func (s *r2Service) Configured() bool { return true }

func (s *r2Service) Put(ctx context.Context, bucket, key string, body io.Reader, contentType string) error {
	_, err := s.client.PutObject(ctx, &s3.PutObjectInput{
		Bucket:      aws.String(bucket),
		Key:         aws.String(key),
		Body:        body,
		ContentType: aws.String(contentType),
	})
	return err
}

func (s *r2Service) URL(ctx context.Context, bucket, key string) (string, error) {
	out, err := s.presigner.PresignGetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(key),
	}, s3.WithPresignExpires(presignTTL))
	if err != nil {
		return "", err
	}
	return out.URL, nil
}

func (s *r2Service) Delete(ctx context.Context, bucket, key string) error {
	_, err := s.client.DeleteObject(ctx, &s3.DeleteObjectInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(key),
	})
	return err
}

/* -------------------------------------------------------------- local ----- */

// localService keeps files under ./uploads/<bucket>/<key> and serves them via
// the API's own /uploads static route. Dev and UAT only — production has R2.
type localService struct {
	cfg  core.Config
	root string
}

func (s *localService) Configured() bool { return false }

// cleanPath refuses anything that could walk out of the root. Keys are
// generated by handlers, but a path check this cheap is not worth skipping.
func (s *localService) cleanPath(bucket, key string) (string, error) {
	p := filepath.Join(s.root, bucket, filepath.FromSlash(key))
	if !strings.HasPrefix(filepath.Clean(p), filepath.Clean(s.root)+string(os.PathSeparator)) {
		return "", fmt.Errorf("storage: refusing path %q", p)
	}
	return p, nil
}

func (s *localService) Put(_ context.Context, bucket, key string, body io.Reader, _ string) error {
	path, err := s.cleanPath(bucket, key)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = io.Copy(f, body)
	return err
}

func (s *localService) URL(_ context.Context, bucket, key string) (string, error) {
	return s.cfg.AppBaseURL + "/uploads/" + bucket + "/" + key, nil
}

func (s *localService) Delete(_ context.Context, bucket, key string) error {
	path, err := s.cleanPath(bucket, key)
	if err != nil {
		return err
	}
	err = os.Remove(path)
	if os.IsNotExist(err) {
		return nil
	}
	return err
}
